# SPDX-License-Identifier: MPL-2.0-or-later
name: CI

on:
  - push
  - pull_request

permissions:
  contents: read
  # implicitly all other scopes not listed become none

jobs:
  ESLint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Setup Deno
        uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2
        with:
          deno-version: v1.x
      - name: Run Deno lint
        run: deno task lint

  checkJs:
    name: Type Check
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Setup Deno
        uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2
        with:
          deno-version: v1.x
      - name: Run type checking
        run: deno task check

  test:
    name: Unittest
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Setup Deno
        uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2
        with:
          deno-version: v1.x
      - name: Run tests
        run: deno task test
      - name: Upload test results
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        if: success() || failure()
        with:
          name: test-results
          path: test-results.json

  event_file:
    name: Event File
    runs-on: ubuntu-latest
    steps:
    - name: Upload
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
      with:
        name: Event File
        path: ${{ github.event_path }}
